import{a as f,S as p,i as g}from"./assets/vendor-DtRopbQG.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const h="49358880-33c4acc352e7c36c64dc2caaa",y="https://pixabay.com/api/",n={params:{key:h,q:"",image_type:"photo",orientation:"horizontal",safesearch:"true"}};function L(s,r){n.params.q=s,f.get(y,n).then(o=>{r(o.data.hits)}).catch(o=>{r([])})}function S(){console.log("show error"),g.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",close:!0,position:"topRight",timeout:3e3})}const c=document.querySelector("ul.gallery");function x(s){return s.map(({comments:r,downloads:o,largeImageURL:i,likes:e,webformatURL:t,views:a,tags:m})=>`<li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${t}" alt="${m}" />
        </a>
        <ul class="image-text-list">
          <li><span class="img-text">Likes</span> ${e}</a></li>
          <li><span class="img-text">Views</span> ${a}</a></li>
          <li><span class="img-text">Comments</span> ${r}</a></li>
          <li><span class="img-text">Downloads</span> ${o}</a></li>
        </ul>
        </li>`).join("")}let b={captionsData:"alt",captionDelay:250};const q=new p(".gallery a",b);function $(s){u(),c.insertAdjacentHTML("beforeend",x(s)),q.refresh()}function u(){c.innerHTML=""}const d=document.querySelector(".loader");function v(){d.classList.remove("loader-hidden")}function w(){d.classList.add("loader-hidden")}const O=document.querySelector(".form"),l=document.querySelector("input"),P=s=>{s.preventDefault();let r=l.value.trim();r!==""&&(u(),v(),L(r,o=>{w(),o.length===0?S():$(o),l.value=""}))};O.addEventListener("submit",P);
//# sourceMappingURL=index.js.map
