import{a as q,S as x,i as p}from"./assets/vendor-DtRopbQG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const $="49358880-33c4acc352e7c36c64dc2caaa",P="https://pixabay.com/api/",l={params:{key:$,q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:1}};async function f(t,o,s){try{l.params.q=t,l.params.page=o;const a=await q.get(P,l);s(a.data.hits,a.data.totalHits)}catch{s([],1,0)}}function B(){console.log("show error"),p.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"16px",messageLineHeight:"1.5",backgroundColor:"#ef4040",close:!0,position:"topRight",timeout:3e3})}function H(){p.info({title:"",message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageLineHeight:"1.5",layout:1,close:!0,position:"topRight",timeout:3e3})}const h=document.querySelector("ul.gallery");function E(t){return t.map(({comments:o,downloads:s,largeImageURL:a,likes:e,webformatURL:r,views:n,tags:w})=>`<li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${r}" alt="${w}" />
        </a>
        <ul class="image-text-list">
          <li><span class="img-text">Likes</span> ${e}</a></li>
          <li><span class="img-text">Views</span> ${n}</a></li>
          <li><span class="img-text">Comments</span> ${o}</a></li>
          <li><span class="img-text">Downloads</span> ${s}</a></li>
        </ul>
        </li>`).join("")}let I={captionsData:"alt",captionDelay:250};const O=new x(".gallery a",I);function y(t){h.insertAdjacentHTML("beforeend",E(t)),O.refresh()}function m(){h.innerHTML=""}const L=document.querySelector(".loader");function S(){L.classList.remove("hidden")}function u(){L.classList.add("hidden")}const b=document.querySelector(".load-btn");function C(){b.classList.remove("hidden")}function d(){b.classList.add("hidden")}function v(){const t=document.querySelector(".gallery-item");if(!t)return;const s=t.getBoundingClientRect().height*2;window.scrollBy({top:s,behavior:"smooth"})}const D=document.querySelector(".form"),g=document.querySelector("input"),M=document.querySelector(".load-btn");let i,c;const z=t=>{t.preventDefault(),i=g.value.trim(),i!==""&&(m(),S(),d(),f(i,1,(o,s)=>{c=1,u(),o.length===0?(B(),d()):(m(),y(o),C(),v()),g.value=""}))};D.addEventListener("submit",z);const A=t=>{t.preventDefault(),c+=1,S(),f(i,c,(o,s)=>{const a=Math.ceil(s/15);c>a?(d(),u(),H()):(u(),y(o),v())})};M.addEventListener("click",A);
//# sourceMappingURL=index.js.map
